### PR TITLE
Updated youtube video link

### PR DESCRIPTION
**Pull request by kaustubhhiware**
This is a test for #33

### CODE REVIEW

**Comment by Demfier** [comment]
At last!
What is the issue in deploying?
Any config issue?

**Comment by kaustubhhiware** [comment]
I'm checking the log in heroku, seems it is downloading Django-2.0, not the mentioned version. I'll check how to use requirements.txt instead of just downloading it straight away

**Comment by kaustubhhiware** [comment]
@Demfier I'll be opening some more PR's to just check if auto-deploy works or not

**Comment by kaustubhhiware** [comment]
See this. The app is deployed, but isn't any good. 

https://c0derunr-pr-37.herokuapp.com/

**Comment by Demfier** [comment]
@kaustubhhiware - Is `heroku local web` successful?

**Comment by Demfier** [comment]
Also, try `pip install -r requirements.txt` in `beta-test` branch and then the ` heroku push origin beta-test` if you haven't

**Comment by kaustubhhiware** [comment]
Umm, the whole idea is once a PR is made, the pipeline should automatically create a review app.
As a contributor, I should not have the burden of dealing with heroku at all.

**Comment by kaustubhhiware** [comment]
`heroku local web` runs perfectly.

The only problem is it tries to install Django 2, not Django 1.11 as specified in requirements.txt (newest commit in master)

**Comment by kaustubhhiware** [comment]
@Demfier sucess at last !
Auto-deploy works perfectly.

To make auto-deploy work, a branch must be made atleast from the current master (at `95ea0e8`)

**Comment by kaustubhhiware** [comment]
To just make sure it works without interference, closing this PR and making a brand new fresh PR with same changes.

**Pull request closed without merging**
