### PR TITLE
Added new languages

### PR DESCRIPTION
**Pull request by kurianbenoy**
I have added a couple of languages and didin't  face any problems while testing

Fixes issue #22

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
Since you will be busy, merging this in.

**Comment by kaustubhhiware** [comment]
@kurianbenoy Let us know if you will be able to continue on this.

You also need to add a default snippet for each language added.

**Comment by kurianbenoy** [comment]
Sorry @kaustubhhiware  I wont be able to continue on this immediately . 

Can you also mention where is the default snippet for each language?

**Comment by kaustubhhiware** [comment]
You need to add that yourself.

**Comment by kurianbenoy** [comment]
Should I add the snippets in Templates ie init.html or elsewhere?

**Comment by kaustubhhiware** [comment]
To reduce strain, I think we'll just make adding new snippets another issue.

Can you squash the 2 commits ? I'll merge right away.

**Review by kaustubhhiware — APPROVED** [review]

**Pull request merged**
