### PR TITLE
used whitenoise

### LINKED ISSUE #7: Setting Debug to False removes access to static files
@kaustubhhiware Either we can use an older version of Django (I don't like the idea though) or we have to configure the server to handle it for us.

### PR DESCRIPTION
**Pull request by 142ayushkumar**
Resolves #7

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
@142ayushkumar seems your master branch is still 4 commits behind.

That's why a review app could not be deployed. Please make sure all the commits on this master are present in your branch before you make a PR

**Comment by 142ayushkumar** [comment]
@kaustubhhiware, please check if the deployed app works or not

**Comment by kaustubhhiware** [comment]
Merging this in. No issues whatsoever.

**Review by kaustubhhiware — APPROVED** [review]
Merging this in. No issues whatsoever.

**Pull request merged**
