### PR TITLE
Htmlhreffix

### LINKED ISSUE #13: Fix links on HTMLviewer
The fork link on HTMLViewer is incorrect: http://c0derunr.herokuapp.com/htmlviewer.

Also, the icon is not set.

Need to correct it to this repository

### PR DESCRIPTION
**Pull request by vishalol**
Fixed link in Html Viewer Page

Resolves #13

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
@VishalCR7 Coding starts December 1.
We will not merge this PR before Dec 1.

You are suggested not to work on anything before that time.
Further PR's before December 1 will be closed.

**Comment by Demfier** [comment]
@VishalCR7 - Can you please open a new PR for this?

**Comment by kaustubhhiware** [comment]
No need for a new P.R, you can just rebase to catch up with the remote

**Comment by kaustubhhiware** [comment]
Additionally, @VishalCR7 , can you also add the icon (.ico) attribute ?

It is mentioned in the issue, but possibly updated after your P.R

**Comment by kaustubhhiware** [comment]
@VishalCR7 please comment if you want to continue on your work. If there is no activity / interaction in the next 3 days, this PR will be closed.

**Pull request closed without merging**
