### PR TITLE
Fixed link ,now fork points to this repository

### LINKED ISSUE #13: Fix links on HTMLviewer
The fork link on HTMLViewer is incorrect: http://c0derunr.herokuapp.com/htmlviewer.

Also, the icon is not set.

Need to correct it to this repository

### PR DESCRIPTION
**Pull request by 142ayushkumar**
Resolves #13 

Previous PR: #46

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
@142ayushkumar you also need to add the favicon for HTMLviewer, as mentioned in the issue.

**Comment by kaustubhhiware** [comment]
Don't worry about counting this in, I'm pretty sure this will be counted as a merged PR.

**Comment by 142ayushkumar** [comment]
@kaustubhhiware  which type of icon to use? a screenshot of repo main page?

**Review by kaustubhhiware — APPROVED** [review]
Since time is of the essence, merging this in. Both tasks completed.

**Pull request merged**
